security:
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Users
    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /
    
    encoders:
        AppBundle\Entity\Users:
            algorithm: bcrypt
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    access_control:
    - { path: ^/dashboard, roles: ROLE_USER, requires_channel: https}
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https}
    
    acl:
        connection: default