# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     validator.unique.DomainExist:
         class: AppBundle\Validator\Constraints\DomainExistValidator
         arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]
         tags:
             - { name: validator.constraint_validator, alias: DomainExistValidator }

     validator.unique.LettersCheck:
         class: AppBundle\Validator\Constraints\LettersCheckValidator
         tags:
             - { name: validator.constraint_validator, alias: LettersCheckValidator }
     
     app.whm:
         class: AppBundle\Utils\Whm

     app.phplake:
         class: AppBundle\Utils\Phplake